apiVersion: apps/v1beta1
kind: Deployment
metadata: 
  name: svc1
spec: 
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: svc1
    spec: 
      containers: 
        - image: "gokul93/hello-world:latest"
          imagePullPolicy: Always
          name: svc1-container
          ports: 
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: svc1-svc
spec: 
  ports: 
     -  port: 8080
        protocol: TCP
        targetPort: 8080
  selector: 
    app: svc1
  type: LoadBalancer
